### ISSUE TITLE
Duplicate sources.list entry in confluentinc/cp-kafka-connect-base:5.5.1

### ISSUE THREAD

**Issue by akhan4u** [confluentinc/kafka-images#120]
Hi team,

We use container `confluentinc/cp-kafka-connect-base:5.5.1` as a base and found that our recent docker builds have been failing when trying to install a few packages with `apt-get install -y` with errors related to duplicate sources.list entries for `https://packages.confluent.io/deb/5.5 stable main`

cat /etc/sources.list (_inside container_)
```
# deb http://snapshot.debian.org/archive/debian/20200607T000000Z jessie main
deb http://deb.debian.org/debian jessie main
# deb http://snapshot.debian.org/archive/debian-security/20200607T000000Z jessie/updates main
deb http://security.debian.org/debian-security jessie/updates main
# deb http://snapshot.debian.org/archive/debian/20200607T000000Z jessie-updates main
deb http://deb.debian.org/debian jessie-updates main
deb [arch=amd64] https://packages.confluent.io/deb/5.5 stable main
deb [arch=amd64] https://packages.confluent.io/deb/5.5 stable main
```

After fixing the duplicate entries locally. The build complaints about **NO_PUBKEY**.

```
W: GPG error: https://packages.confluent.io stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B1DA6120C2BF624
W: Duplicate sources.list entry https://packages.confluent.io/deb/5.5/ stable/main amd64 Packages (/var/lib/apt/lists/packages.confluent.io_deb_5.5_dists_stable_main_binary-amd64_Packages.gz)
```

We are able to work around the issue by using the `--force-yes` flag with `apt-get install -y` commands. 
Can you please check about the **NO_PUBKEY** end on your repository?

**Comment by andrewegel** [comment]
`8B1DA6120C2BF624` is the new key:

https://docs.confluent.io/platform/current/installation/installing_cp/overview.html#confluent-signing-keys

`670540c841468433` was revoked:

https://www.confluent.io/blog/confluent-update-regarding-codecov-incident

All packages signed on packages.confluent.io were resigned with `8B1DA6120C2BF624`, but docker images were never rebuilt with the newly signed keys & re-signed packages. In general `apt update`-ing to the next CP version isn't recommended:

https://docs.confluent.io/platform/current/release-notes/changelog.html#cp-docker-images

And has since been removed from newer docker images. 

To work around your issue, you can re-import the new public key via:

```
wget -qO - https://packages.confluent.io/deb/5.5/archive.key | sudo apt-key add -
```

Couple of suggestions:
* Use the `-ubi8` suffixed images, they're based on Redhat8 and not an EoL Debian8.
* Use the newer 5.5.x line of images. Thats 5.5.6-10-ubi8 today, and later on this month, a 5.5.7-1-ubi8 image will appear on the DockerHub
