### ISSUE TITLE
Struggling to get crontab working for docker appuser in image cp-kafka-connect-base

### ISSUE THREAD

**Issue by ceecer1** [confluentinc/kafka-images#151]
I am using below image but struggling to get crontab working.

FROM confluentinc/cp-kafka-connect-base:6.2.1

Can someone pls help on this ?

**Comment by andrewegel** [comment]
Docker containers aren't designed to run things on a cron schedule. So you're left with some other "hacky" solutions such as https://stackoverflow.com/questions/37458287/how-to-run-a-cron-job-inside-a-docker-container

If this is related to kubernetes and running workloads on a cron schedule, you can look here: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by ceecer1** [comment]
Hi @andrewegel , I am not trying to run docker container on a cron schedule. Let me put a bit more clarity here.

I am using below docker file:

FROM confluentinc/cp-kafka-connect-base:6.2.1

RUN   confluent-hub install --no-prompt confluentinc/kafka-connect-jms:11.0.11

USER root
RUN  yum install -y jq cronie
USER appuser

... Then. run the actual connect-distributed component will start the kafka connect container.

But apparently jms connector seems to be idle and throwing errors for no reason after few hours.

So I wanted to run crontab to check health of that jms connector periodically and restart the jms connector. But the cron job only runs when the docker container user is root, since docker containers are not supposed to run via root, I tried to run via appuser. The appuser doesn't seem to have enough permission to start crontab and run as expected.

Only reason I need cron working is to keep the connectors working. Do you know how this can be achieved or is there any other pattern to health check these individual connectors and restart them as required.

I am running this on AWS ECS not in k8s, so please any guidance will be very helpful on this.

Thanks a lot.

**Comment by andrewegel** [comment]
Your problem here isn't specific to Confluent or our Docker Images - Your questions are mainly around the container process model. I'll share with you some links/ideas, but this where our help will end, as its going to be on you to formulate your own home brewed solution, possibly even asking the Docker Folks what the best practice is. So here:

* How to run multiple processes (Running a cron scheduler & the JMS service): https://docs.docker.com/config/containers/multi-service_container/
* How to run crond in docker as non-root: https://stackoverflow.com/questions/63046301/how-to-run-cron-as-non-root-in-alpine
* And my original link on how to run cron in a container: https://stackoverflow.com/questions/37458287/how-to-run-a-cron-job-inside-a-docker-container

Combining three of those solutions you can likely come up with a home brewed solution to accomplish your goal.

And a reminder, this isn't anything specific to Confluent's software, you could swap out Confluent's service for say nginx, apache, gunicorn, <some-other-server-process> and your solutions would likely be the same. Since this isn't anything Confluent-related here, I'm closing this issue out, as its not specific to Confluent or these images.

> But apparently jms connector seems to be idle and throwing errors for no reason after few hours.

Yes, I saw that you opened another issue as well about this, and the JMS connector is an enterprise connector, so please reach out to support@confluent.io as per my comment in:

https://github.com/confluentinc/kafka-images/issues/150#issuecomment-1072789420
