### ISSUE TITLE
Kafka log4j 1.x Obsolete Vulenerability 

### ISSUE THREAD

**Issue by mrk9676** [confluentinc/kafka-images#157]
Hi Team,

All of us know Kafka is still using log4j 1.x jar files even though Log4j 1.x has reached End of Life in 2015 and is no longer supported. So it became obsolete vulnerability for Kafka.

Are there any alternatives to replace log4j 1.x in present Kafka(docker images) or Is there any development is going on to replace these log4j1.x? If yes, is there any ETA provided by Kafka team ?

Please provide me an update if we have any ?

**Comment by andrewegel** [comment]
You'll want to follow what the Apache/Kafka project is doing: https://issues.apache.org/jira/browse/KAFKA-9366. Once its in an Apache Kafka release, the next CP release will update to log4j2.

You can also watch for security bulletins around security related things here: https://support.confluent.io/hc/en-us/sections/360008413952-Security-Advisories-and-Security-Release-Notes

If you look at the notes for 7.0.2 - you can see there has been some work to "harden" Confluent's log4j1.x fork: https://support.confluent.io/hc/en-us/articles/4887384246420-Security-Release-Notes-for-CP-7-0-2

Otherwise there are no plans that can be shared externally. Reach out to your Confluent account manager or support and maybe some information can be shared with you.
