### ISSUE TITLE
Install jq in kafka-connect-base

### ISSUE THREAD

**Issue by toddkblake** [confluentinc/kafka-images#165]
Given the frequency of referencing `jq` in documentation ([example](https://docs.confluent.io/home/connect/self-managed/monitoring.html#common-rest-examples)) and training videos for Kafka Connect, would it make sense to install it in the base image? 

As was mentioned in https://github.com/confluentinc/kafka-images/issues/60, the change to using an app user that cannot install dependencies in the image at runtime requires extending the base image just to install `jq`. 

Rather than maintaining an extension image, it would be preferable to allow the app user to use `jq` to perform common REST API operations from within a running Kafka Connect worker instance.

**Comment by andrewegel** [comment]
Same reasons in #60 : No, we will not install `jq` because:

* It keeps image sizes small
* It keeps CVE surface area small - If you glance at this projects issues list, there are a lot of reported CVEs, so staying on top of them by not introducing unnecessary software (`jq` in this case) for the runtime is a necessity. 

Work arounds:

* Extend the image for your own needs
* Run `docker exec -u 0 <container-id> /bin/bash` and from there install what you need.
* If this is in a K8 context, use Ephemeral Containers to "attatch" a new container with the perscribed software you want: https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/
