### ISSUE TITLE
Root user/sudo on 6.x images

### ISSUE THREAD

**Issue by ankon** [confluentinc/kafka-images#60]
It seems that with the 6.x platform images everything runs as "appuser", and there's no sudo or such configured on the images.

In our (Kubernetes, AWS MSK) environment we use the images not necessarily to run Kafka itself, but rather as very convenient images for getting the Kafka CLI tools. Usually the flow in our documentation to do any Kafka maintenance is:

1. Use `kubectl run ... --image confluentinc/cp-kafka` to bring up a helper pod
2. Connect to that running pod
3. **Install additional tools such as `jq`, `vim`, ...**
4. Run one or more Kafka CLI tools (`kafka-topics`, `kafka-consumer-groups`, `kafka-reassign-partitions`)

With the 6.x images I cannnot see a way to make step 3 work, and with that it seems I would have to fork/clone/...(?) the images or build my own to provide suitable means.

Assuming this is a reasonable use-case: What do you think would be the best way to support it?

**Comment by andrewegel** [comment]
You will want to extend the images: https://docs.confluent.io/platform/current/installation/docker/development.html#extending-images as mentioned - Having sudo/sudoer rules that allow root privilege escalation in the container is not a good idea to implement en-mass. Docker Images were designed in mind to be "extendable" for very situations like this.

I'm closing this because this is not an issue/bug - its an intentional security feature of the cp images.
